# Generated by Django 3.0.1 on 2019-12-29 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_account', models.DateTimeField(blank=True, default=None, null=True, verbose_name='дата записи')),
                ('total_count', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='единиц товара продано')),
                ('total_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='сумма продажи')),
                ('revenue', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='выручка')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='изменен')),
            ],
            options={
                'verbose_name': 'продажи',
                'verbose_name_plural': 'Журнал счетов',
            },
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='адрес')),
                ('manager', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='менеджер')),
                ('shop_phone', models.CharField(blank=True, default=None, max_length=11, null=True, verbose_name='телефон магазина')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_inn', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='ИНН поставщика')),
                ('supplier_name', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Название поставщика')),
                ('supplier_adress', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='адрес поставщика')),
                ('supplier_phone', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='телефон поставщика')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='добавлен')),
            ],
            options={
                'verbose_name': 'поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='имя продавца')),
                ('seller_phone', models.CharField(blank=True, default=None, max_length=11, null=True, verbose_name='телефон продавца')),
                ('active', models.BooleanField(default=True)),
                ('shop_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Shops', verbose_name='id магазина')),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавцы',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('status', models.CharField(blank=True, choices=[('processed', 'обработана'), ('not processed', 'не обработана')], max_length=20, verbose_name='статус')),
                ('products', models.TextField(blank=True, verbose_name='Товары для отгрузки')),
                ('seller_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Sellers', verbose_name='Имя продавца')),
            ],
            options={
                'verbose_name': 'заявка на поступление товаров',
                'verbose_name_plural': 'заявки на поступление товаров',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='наименование')),
                ('price_opt', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='оптовая цена')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='розничная цена')),
                ('left', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='остаток в наличии')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='добавлен')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='изменен')),
                ('supplier', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Suppliers', verbose_name='поставщик')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductInAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmb', models.IntegerField(default=1, verbose_name='количество')),
                ('price_per_item', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='стоимость')),
                ('price_per_item_opt', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='оптовая стоимость')),
                ('total_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='суммарная стоимость')),
                ('total_count', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='суммарное количество')),
                ('total_price_opt', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='суммарная оптовая стоимость')),
                ('revenue', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='выручка')),
                ('account', models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Accounts', verbose_name='номер записи')),
                ('product', models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Products', verbose_name='наименование')),
            ],
            options={
                'verbose_name': 'Товар в счете',
                'verbose_name_plural': 'Товары в счете',
            },
        ),
        migrations.AddField(
            model_name='accounts',
            name='seller_name',
            field=models.ForeignKey(blank=True, default=None, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Sellers', verbose_name='имя продавца'),
        ),
    ]
