# Generated by Django 3.0.1 on 2019-12-29 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinaccount',
            name='revenue',
        ),
        migrations.RemoveField(
            model_name='productinaccount',
            name='total_price_opt',
        ),
    ]
