# Generated by Django 3.0.1 on 2019-12-29 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20191229_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='имя менеджера')),
                ('manager_phone', models.CharField(blank=True, default=None, max_length=11, null=True, verbose_name='телефон менеджера')),
            ],
            options={
                'verbose_name': 'менеджер',
                'verbose_name_plural': 'менеджеры',
            },
        ),
        migrations.RemoveField(
            model_name='request',
            name='seller_name',
        ),
        migrations.RemoveField(
            model_name='sellers',
            name='shop_id',
        ),
        migrations.RemoveField(
            model_name='shops',
            name='manager',
        ),
        migrations.AddField(
            model_name='sellers',
            name='adress',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Shops', verbose_name='адрес магазина'),
        ),
        migrations.AddField(
            model_name='request',
            name='manager_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Managers', verbose_name='Имя менеджера'),
        ),
        migrations.AddField(
            model_name='shops',
            name='manager_name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Managers', verbose_name='менеджер'),
        ),
    ]
